import type { Env, RegulatoryEvent, RiskScoreOutput } from '../types';

const REPO_OWNER = 'ross0nline';
const REPO_NAME = 'acis';
const BASE_BRANCH = 'master';
const GITHUB_API = 'https://api.github.com';

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 50)
    .replace(/-+$/, '');
}

async function githubRequest(
  token: string,
  method: string,
  path: string,
  body?: unknown,
): Promise<Response> {
  return fetch(`${GITHUB_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'ACIS-Worker/1.0',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
}

function alertMarkdown(event: RegulatoryEvent, scored: RiskScoreOutput | null): string {
  const date = new Date().toISOString().split('T')[0];
  const deadline = scored?.deadline ? `\n**Compliance Deadline:** ${scored.deadline}` : '';
  const remediation = scored?.remediation_step ?? 'Review the linked document and assess impact on current compliance posture.';

  return `# Compliance Alert: ${event.title}

**Date Detected:** ${date}
**Source:** ${event.source}
**Risk Score:** ${event.risk_score}/10
**HIPAA Impact Area:** ${scored?.impacted_field ?? 'Unknown'}${deadline}

## Summary

${scored?.summary ?? event.summary ?? 'No summary available.'}

## Required Action

${remediation}

## Source

[${event.title}](${event.url})

---
*Auto-generated by ACIS Regulatory Pulse — Event ID ${event.id}*
`;
}

function prBody(event: RegulatoryEvent, scored: RiskScoreOutput | null, filePath: string): string {
  const deadline = scored?.deadline ? `\n- **Compliance Deadline:** ${scored.deadline}` : '';
  return `## High-Risk Regulatory Alert

ACIS detected a regulatory event with risk score **${event.risk_score}/10** requiring compliance review.

### Event Details
- **Title:** ${event.title}
- **Source:** ${event.source}
- **Risk Score:** ${event.risk_score}/10
- **HIPAA Impact Area:** ${scored?.impacted_field ?? 'Unknown'}${deadline}
- **Source URL:** ${event.url}

### Claude Risk Assessment
${scored?.summary ?? event.summary ?? 'No assessment available.'}

### Required Action
${scored?.remediation_step ?? 'Review and assess impact on current compliance posture.'}

### Files Added
- \`${filePath}\`

---
*Auto-generated by [ACIS](https://acis.rossonlineservices.com) — Event ID ${event.id}*
`;
}

export async function createCompliancePR(
  env: Env,
  event: RegulatoryEvent,
  scored: RiskScoreOutput | null,
): Promise<void> {
  if (!env.GITHUB_TOKEN) return;

  const token = env.GITHUB_TOKEN;
  const date = new Date().toISOString().split('T')[0];
  const slug = slugify(event.title);
  const branchName = `compliance/alert-${date}-${event.id}`;
  const filePath = `docs/compliance-alerts/${date}-${slug}.md`;

  // 1. Get base branch SHA
  const refResp = await githubRequest(token, 'GET', `/repos/${REPO_OWNER}/${REPO_NAME}/git/ref/heads/${BASE_BRANCH}`);
  if (!refResp.ok) return;
  const refData = await refResp.json() as { object: { sha: string } };
  const baseSha = refData.object.sha;

  // 2. Create branch — 422 means it already exists (idempotent)
  const branchResp = await githubRequest(token, 'POST', `/repos/${REPO_OWNER}/${REPO_NAME}/git/refs`, {
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });
  if (!branchResp.ok && branchResp.status !== 422) return;

  // 3. Create alert file
  const content = btoa(unescape(encodeURIComponent(alertMarkdown(event, scored))));
  const fileResp = await githubRequest(token, 'PUT', `/repos/${REPO_OWNER}/${REPO_NAME}/contents/${filePath}`, {
    message: `compliance(alert): ${event.title.slice(0, 70)}`,
    content,
    branch: branchName,
  });
  if (!fileResp.ok && fileResp.status !== 422) return;

  // 4. Create PR — 422 means PR already exists for this branch
  await githubRequest(token, 'POST', `/repos/${REPO_OWNER}/${REPO_NAME}/pulls`, {
    title: `[COMPLIANCE ALERT] ${event.title.slice(0, 60)} (Risk: ${event.risk_score}/10)`,
    body: prBody(event, scored, filePath),
    head: branchName,
    base: BASE_BRANCH,
    labels: ['compliance', 'auto-generated'],
  });
}
